### PR TITLE
Update pandas function, convert percentiles NAN values issue fixed, and .gitignore minor update

### PR DESCRIPTION
**Pull request by mjorgen1**
To close the issue about pandas I opened a little while back. After updating the pandas functionality, I also needed to update the code so that the convert percentiles function would work correctly (otherwise it was returning NAN values because of the v.index). I also added the data folder and idea folder to the .gitignore.

### CODE REVIEW

**Comment by mrtzh** [comment]
Hi, I'm excited about all the work you put into this. I've been getting updates from this pull request. I haven't dug in. Before I do, can you tell me if this is intended to go into this repository? It looks like this is the code for a different project. The readme file you want to commit seems to describe a different project that you co-authored. If this is the code for that, I think it would be more customary to put that in a separate repository. This repository should probably only contain what's needed to reproduce the figures in the delayed impact paper. Bug fixes are of course welcome.

**Comment by mjorgen1** [comment]
Hi Moritz, I opened this pull request because when I originally forked the repository, I wasn't able to get the code to run properly. So I fixed the issue--after updating the pandas functionality, I also needed to update the code so that the convert percentiles function would work correctly (otherwise it was returning NAN values because of the v.index). I also added the data folder and idea folder to the .gitignore. However, I did NOT realize my work (after fixing the issue) on my forked repository was contributing to this pull request. My deepest apologies. I will close this now.

**Comment by lydiatliu** [comment]
Thanks both for checking in and clarifying/closing this pull request! I'm glad the new pandas compatibility issue worked out in the end in your project, Mackenzie.

**Comment by mrtzh** [comment]
Thanks and no worries at all.

**Pull request closed without merging**
